version: '3.3'

services:
  app:
    container_name: app
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - .rabbitmq:/var/lib/rabbitmq
